### PR TITLE
[14.0][ADD] hr_timesheet_sheet_daily

### PR DESCRIPTION
**Pull request by adriresu**

### CODE REVIEW

**Comment by dalonsod** [comment]
@adriresu could you take a look at code and test last changes?

**Comment by adriresu** [comment]
Tested locally, looks good.

**Review by dalonsod — APPROVED** [review]
Tested with latest changes (basically make date_end stored) in customer test environment, 👍

**Comment by dalonsod** [comment]
I've also made squash, so let's merge it!

cc @ChristianSantamaria

**Pull request merged**
